version: "3"
services:
 web:
   build: .
   command: python manage.py runserver 0.0.0.0:8000
   working_dir: /code
   ports:
     - 8000:8000
   volumes:
     - .:/code
   depends_on:
     - db
 db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ROOTPASS
      MYSQL_DATABASE: c-db
      MYSQL_USER: hiro
      MYSQL_PASSWORD: SQL_PASS
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  db-data: